#!/bin/bash

if [[ "$1" == "" ]]
	then git pull; git log --oneline
else	
	while [[ "$1" != "" ]]; do
		git add "$1"
		shift
	done
	read -r -p  'Insert commit message: '  msg
		git commit -m "$msg"
		git push
fi